spring.application.name=TicketTally
spring.datasource.url=jdbc:mysql://localhost:3306/tickettally_db?useSSL=false
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=ThisIsMyVerySecureSecretKeyForJwtHS256Authentication123456789
jwt.expiration=3600000
server.port=5525